kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # namespace: default
  name: pod-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-role
rules:
  - apiGroups: ["apps"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
