apiVersion: v1
kind: Service
metadata:
  name: license-management-system-customer-service
spec:
  selector:
    app: license-management-system-customer-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
