apiVersion: v1
kind: Service
metadata:
  name: my-node-port-service
spec:
  type: NodePort
  ports:
    - port: 81  # The port your service will listen on
      targetPort: 8081  # The port your pods are listening on
      nodePort: 30080  # The external port you'll use to access the service
  selector:
    app: license-management-system-customer-label  # Replace this with the labels matching your pods
