server:
  port: 8081

license:
  key:
    file:
      public: "public_key.txt"
  deployment:
    name: "license-management-system-customer-deployment"
  label:
    node:
      master: "node-role.kubernetes.io/control-plane"
  secret:
    public-key:
      secret-name: "public-key-secret"
      secret-label: "public-key-label"
      data:
        key: "public-key"
    digital-signature:
      secret-name: "digital-signature-secret"
      secret-label: "digital-signature-label"
      data:
        key: "digital-signature"
    user-information:
      secret-name: "user-information-secret"
      secret-label: "user-information-label"
      data:
        key:
          id: "id"
          license-key: "license-key"
          expiration-date: "expiration-date"
          customer-name: "customer-name"