kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # namespace: default
  name: secret-cluster-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: secret-role
rules:
  - apiGroups: ["apps"]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
