apiVersion: apps/v1
kind: Deployment
metadata:
  name: license-management-system-customer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: license-management-system-customer-label
  template:
    metadata:
      labels:
        app: license-management-system-customer-label
    spec:
      containers:
        - name: license-management-system-customer
          image: license-management-system-customer-image:v1
