kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # namespace: default
  name: deployment-cluster-role
rules:
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "delete"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: deployment-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "delete"]
